config/routes.rb
Yumhub::Application.routes.draw do

  get "noms/show"

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  
  resources :users, only: [:show], path: '' do
    resources :noms
    resources :follows, only: [:create, :destroy]
    member do
      get :followers
      get :following
    end
  end

  root to: 'home#index'
  
  

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/nom.rb
class Nom < ActiveRecord::Base
  attr_accessible :description, :ingredients, :name, :steps, :category, :user_id
  
  CATEGORY = ['Dinner', 'Lunch', 'Breakfast', 'Snack', 'Drink', 'Alcohol']
  
  belongs_to :user
  
  validates :name, presence: true, length: { maximum: 140 }
  validates :category, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :ingredients, presence: true
  validates :steps, presence: true
  validates :user_id, presence: true
  
  default_scope order: 'created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  extend FriendlyId
  friendly_id :username, use: :slugged
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
  attr_accessible :login
  attr_accessor :login
  
  acts_as_followable
  acts_as_follower
  
  has_many :noms
  
  UNUSEABLE_USERNAMES = ["meals", "about", "login", "log_in", "signup", "sign_up", "signin", "sign_in", "logout", "log_out", "signout", "sign_out"] 
  
  validate :username_useable?
  validates :username, presence: true, uniqueness: { case_sensitive: true }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
  
  
  # Username validation
  def username_useable?
    if UNUSEABLE_USERNAMES.include?(username.downcase)
      errors.add(:username, "not valid.")
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
 
  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
  end
 
  def destroy
    @user = User.find(params[:user_id])
    current_user.stop_following(@user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @nom = Nom.new
    @noms = Nom.all
    unless current_user.nil?
      @friends_noms = Nom.where(user_id: current_user.following_users.map(&:id))
    end
  end
end

app/controllers/noms_controller.rb
class NomsController < ApplicationController
  respond_to :html, :json
  
  def new
    @nom = Nom.new
  end
  
  def create
    @nom = current_user.noms.build(params[:nom])
    if @nom.save
      flash.now[:success] = "Nom created!"
		else
      flash.now[:error] = @nom.errors.full_messages
      @noms = Nom.all
		end
		respond_to do |format|
      # format.html
      format.js
    end
  end
  
  def show
    @user = User.find_by_username(params[:username])
    @nom = Nom.find_by_id(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @nom = Nom.new
    @noms = Nom.where(user_id: User.find(@user))
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
  end
  
  def following
    @user = User.find(params[:id])
    @following = @user.all_following
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_header_links(*args)
    # Must be passed in like [controller, action] for this logic to work
    link_class = ''
    args.each do |arg|
      controller = arg[0]
      action = arg[1]
      link_class = 'active' if params[:action] == action and params[:controller] == controller
    end
    link_class
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    flash_alerts = []
    error_key = 'errors.messages.not_saved'
    
    if !flash.empty?
      flash_alerts.push(flash[:error]) if flash[:error]
      flash_alerts.push(flash[:alert]) if flash[:alert]
      flash_alerts.push(flash[:notice]) if flash[:notice]
      error_key = 'devise.failure.invalid'
    end
    
    return "" if resource.errors.empty? && flash_alerts.empty?
    errors = resource.errors.empty? ? flash_alerts : resource.errors.full_messages
    
    messages = errors.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t(error_key, :count    => errors.count,
                                 :resource => resource.class.model_name.human.downcase)
    
    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML
    
    html.html_safe
  end
  
  def current_user?(user)
    user == current_user
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
  def determine_user_no_following
    if current_user?(@user)
      "You aren't following anyone."
    else
      @user.username + " isn't following anyone."
    end
  end
  
  def determine_user_no_followers
    if current_user?(@user)
      "You have no followers."
    else
      @user.username + " has no followers."
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/noms_helper.rb
module NomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def determine_user_nom_header
    if current_user?(@user)
      "Your Noms!"
    else
      @user.username + "'s Noms!"
    end
  end
  
end

app/views/follows/create.js.erb
$('#follow_user').html('<%= escape_javascript(render partial: "shared/follow_user", locals: {user: @user}) %>');

app/views/follows/destroy.js.erb
$('#follow_user').html('<%= escape_javascript(render partial: "shared/follow_user", locals: {user: @user}) %>');

app/views/home/....html.erb
<h1>Home#...</h1>
<p>Find me in app/views/home/....html.erb</p>

app/views/home/index.html.haml
.row-fluid
  .span4{style: "margin-top:50px;border:1px solid #000000;border-radius:4px;padding:3px 7px;"}
    -if user_signed_in?
      %h6
      = render 'noms/create'
    -else
      %h6
      = render 'devise/sessions/login'
      %h4 New to YumHub? Sign up!
      = render 'devise/registrations/signup'
  .span8.pull-right.rightside_feed
    %h4{style: "display:inline-block;"} Noms!
    %ul.nav.nav-pills.pull-right{style: "margin-top:5px;margin-bottom:-10px;"}
      %li.active
        %a{href: '#'} All
      %li
        %a{href: '#'} Followed
    = render 'shared/feed'

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  .notifications.top-center
    %div{class: "alert alert-#{key} in fade"}
      %button.close{"data-dismiss" => "alert", type: "button"} &times;
      -if value.is_a?(String)
        = value
      -else
        -if value.nil?
          = devise_error_messages
        -else
          - value.each do |msg|
            %li
              = msg

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %ul.nav
        %li{class: active_header_links(["home", "index"])}= link_to "Home", root_path
        %li{class: active_header_links(['#', '#'])}= link_to "Connect", '#'
        -if user_signed_in?
          %li{class: active_header_links(['users', 'show'], ['users', 'following'], ['users', 'followers'])}= link_to "Me", current_user
          %li= link_to "Logout", destroy_user_session_path, :method => :delete
        -else
          %li= link_to "Login", new_user_session_path
          %li= link_to "Sign Up", new_user_registration_path
      %form.navbar-search.pull-right
        %input.search-query.span2{type: "text", placeholder: "Search", "data-focus" => "false", autocomplete: "off"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title YumHub
    = stylesheet_link_tag   "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    #flash_messages
      = render 'layouts/flash_messages'
    .container
      = yield

app/views/noms/_create.html.haml
= form_for [current_user, @nom], remote: true do |f|
  = f.text_field :name, placeholder: "Name", class: "span12"
  = f.select :category, options_for_select(Nom::CATEGORY, @nom.category), {prompt: "Category"}, {class: "span12"}
  = f.text_area :description, placeholder: "Description", rows: "5", class: "span12 only_vertical"
  = f.text_area :ingredients, placeholder: "Ingredients", rows: "5", class: "span12 only_vertical"
  = f.text_area :steps, placeholder: "Steps", rows: "5", class: "span12 only_vertical"
  = f.submit "Post", class: "btn btn-primary post_nom"

app/views/noms/create.html.erb
<h1>Noms#create</h1>
<p>Find me in app/views/noms/create.html.erb</p>

app/views/noms/create.js.erb
$("#flash_messages").html("<%= escape_javascript(render partial: 'layouts/flash_messages', locals: {flash: flash}) %>")

if ("<%= @nom.name %>" && "<%= @nom.category %>" && "<%= @nom.category %>" && "<%= @nom.ingredients %>" && "<%= @nom.steps %>") {
  $("#nom_name").val('')
  $("#nom_category").val('')
  $("#nom_description").val('')
  $("#nom_ingredients").val('')
  $("#nom_steps").val('')

  $("<%= escape_javascript(render partial: 'shared/feed_items', locals: {nom: @nom}) %>").prependTo("#nom_feed").hide().slideDown()
}

app/views/noms/show.html.erb
<h1>Noms#show</h1>
<p>Find me in app/views/noms/show.html.erb</p>

app/views/shared/_feed.html.haml
.clearfix
%ul#nom_feed
  - if @noms.any?
    - @noms.each do |nom|
      = render 'shared/feed_items', nom: nom

app/views/shared/_feed_items.html.haml
%li.single_nom
  .userimage_nom
    = link_to image_tag("tempuserimage.png", alt: "user image"), user_path(nom.user.slug)
  .info_nom
    %strong= link_to nom.user.slug, user_path(nom.user.slug)
    \-
    %strong #{nom.name}
    %div
      = nom.description

app/views/shared/_follow_user.html.haml
- unless current_user?(@user)
  - if current_user.following?(@user)
    = button_to "Unfollow", user_follow_path(@user.to_param, current_user.get_follow(@user).id), method: :delete, remote: true, class: "btn btn-inverse"
  - else
    = button_to "Follow", user_follows_path(@user.to_param), remote: true, class: "btn"

app/views/users/followers.html.haml
.row-fluid
  .span4{style: "margin-top:50px;border:1px solid #000000;border-radius:4px;padding:3px 7px;"}
    / -if current_user?(@user)
    /   %h6
    /   = render 'noms/create'
    / -else
    User stuff here!
  .span8.pull-right.rightside_feed
    %h4{style: "display:inline-block;"} Followers
    - if @followers.any?
      %ul
        = @user.followers_count
        - @followers.each do |fl|
          %li
            = link_to fl.username, user_path(fl.username)
    - else
      = determine_user_no_followers

app/views/users/following.html.haml
.row-fluid
  .span4{style: "margin-top:50px;border:1px solid #000000;border-radius:4px;padding:3px 7px;"}
    / -if current_user?(@user)
    /   %h6
    /   = render 'noms/create'
    / -else
    User stuff here!
  .span8.pull-right.rightside_feed
    %h4{style: "display:inline-block;"} Following
    - if @following.any?
      %ul
        = @user.follow_count
        - @following.each do |fl|
          %li
            = link_to fl.username, user_path(fl.username)
    - else
      = determine_user_no_following

app/views/users/show.html.haml
.row-fluid
  .span4{style: "margin-top:50px;border:1px solid #000000;border-radius:4px;padding:3px 7px;"}
    -if current_user?(@user)
      %h6
      = render 'noms/create'
    -else
      User stuff here!
      .clearfix
      %br
      #follow_user
        = render 'shared/follow_user', locals: { user: @user }
  .span8.pull-right.rightside_feed
    %h4{style: "display:inline-block;"} #{determine_user_nom_header}
    = render 'shared/feed'